#!/usr/bin/perl
#
##############################################################################################################
# Teamspeak 3 Users Top10 Munin plugin
#
# This script monitors the top 10 Users by online time on your TS3 server.
# It relies on a periodically updated database. This can be done e.g. by this script:
#
# https://github.com/mkirbst/webts-ng
# 
#### CONFIG ####
#
# Please set the corret login credentials for the mysql database in line 26.
#
##############################################################################################################

use strict;
use Munin::Plugin;
use DBI;

# sleep to give the database time to get updated, or we get inconsistent values
sleep(8);

my ($db_user, $db_name, $db_pass) = ('ts3queryuser', 'ts3db', 'mysqlpassword');

if ($ARGV[0] and $ARGV[0] eq "autoconf") {
	print "yes\n";
	exit 0;
}

if ($ARGV[0] and $ARGV[0] eq "config") {
	print "graph_args --base 1000  --logarithmic --units=si\n"; 	# better scaling if some users gain very high values
	print "graph_vlabel Users\n";
	print "graph_title TS3 top countries by users\n";
	print "graph_category teamspeak\n";
	print "graph_info This grah shows user count per country on this teamspeak server.\n";

	# open connection to database
	my $dbh = DBI->connect("DBI:mysql:database=$db_name", $db_user, $db_pass);

	# CLDBID CLNAME Minutes
	my $sth = $dbh->prepare(' SELECT country,COUNT(CLNAME) AS usercount FROM ts3top WHERE country!="NULL" GROUP BY country; ');

	$sth->execute() or die $DBI::errstr;;

	# FETCHROW ARRAY

	my @results;
	my $cleanname;

	while (@results = $sth->fetchrow()) {
		print $results[0].".label ".$results[0]."\n"; # id42: clientname - get rid of users with same name 
	}
	$sth->finish();

	## disconnect from database
	$dbh->disconnect();

	exit 0;
}        

# open connection to database
my $dbh = DBI->connect("DBI:mysql:database=$db_name", $db_user, $db_pass);

# CLDBID CLNAME Minutes
my $sth = $dbh->prepare('SELECT country,COUNT(CLNAME) AS usercount FROM ts3top WHERE country!="NULL" GROUP BY country; ');

$sth->execute() or die $DBI::errstr;;

# FETCHROW ARRAY
my @results;

while (@results = $sth->fetchrow()) {
	print $results[0].".value ".$results[1]."\n";
}
$sth->finish();

## disconnect from database
$dbh->disconnect();

exit 0;


       

